using System.Text.Json;
using Caseflow.Agent;
using Caseflow.Models;
using Caseflow.Services.Llm;

namespace Caseflow.Tools;

public sealed class DraftClientEmailTool(ILlmProvider llm) : ITool
{
    public string Name => "DraftClientEmail";

    public string Description =>
        "Draft a status update email to the client about the case. Uses gpt-5.4-mini for the generation. " +
        "Policy is AskHuman: even though the prototype never sends, the agent stops for human approval " +
        "before generating client-facing content.";

    public ToolPolicy Policy => new(
        ToolPolicyDecision.AskHuman,
        "Client communications must never be sent autonomously, even when the draft is generated by code.");

    public async Task<ToolResult> ExecuteAsync(
        CaseSnapshot snapshot,
        JsonElement input,
        CancellationToken ct = default)
    {
        var request = new LlmCompletionRequest(
            Tier: LlmTier.Mini,
            SystemPrompt: LlmPrompts.DraftClientEmailSystem,
            UserMessage:
                $"Draft an update email for client {snapshot.Case.ClientName}. " +
                $"Current case state: {snapshot.State}. " +
                $"{snapshot.Analyses.Count} analyses completed; {snapshot.Extractions.Count} extractions on file.",
            SchemaName: EmailDraftSchema.SchemaName,
            JsonSchema: EmailDraftSchema.Json,
            DocumentPath: null);

        var draft = await llm.CompleteAsync<EmailDraft>(request, ct);

        return new ToolResult(
            Success: true,
            Confidence: 1.0,
            OutputSummary: $"Draft email composed — subject: \"{draft.Subject}\". Never sent: SMTP is out of scope.",
            Error: null,
            NewState: null,
            Persist: null);
    }
}
